services:
  contenedor1:
    build: .
    container_name: contenedor1
    volumes:
      - datos_publicos:/usr/src/app/sync_files/public
      - datos_privados1:/usr/src/app/sync_files/private/contenedor1
      - contenedores:/usr/src/app/sync_files/registro
    environment:
      - NOMBRE_CONTENEDOR=contenedor1
    networks:
      - synchrontainer
    ports:
      - "3000:5000"

  contenedor2:
    build: .
    container_name: contenedor2
    volumes:
      - datos_publicos:/usr/src/app/sync_files/public
      - datos_privados2:/usr/src/app/sync_files/private/contenedor2
      - contenedores:/usr/src/app/sync_files/registro
    environment:
      - NOMBRE_CONTENEDOR=contenedor2
    networks:
      - synchrontainer
    ports:
      - "3001:5000"

  contenedor3:
    build: .
    container_name: contenedor3
    volumes:
      - datos_publicos:/usr/src/app/sync_files/public
      - datos_privados3:/usr/src/app/sync_files/private/contenedor3
      - contenedores:/usr/src/app/sync_files/registro
    environment:
      - NOMBRE_CONTENEDOR=contenedor3
    networks:
      - synchrontainer
    ports:
      - "3002:5000"

volumes:
  datos_publicos:
  datos_privados1:
  datos_privados2:
  datos_privados3:
  contenedores:

networks:
  synchrontainer: